<a href="https://colab.research.google.com/github/manoj07d/Data-Analysis-ETL-Project-1/blob/main/Product_Orders_ETL1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ETL project using Python & SQLServer database on GitHub dataset.**

## **Extracting Data from GitHub**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/manoj07d/datasets/master/office_orders.csv')
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

## **Transforming the data**

### **Replacing 'Not Available','unknown' values with NaN**

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/manoj07d/datasets/master/office_orders.csv', na_values=['Not Available','unknown'])

In [ ]:
# To check the 'Ship Mode' column once more
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

### **Correcting the Data types**

In [ ]:
df.dtypes

Order Id             int64
Order Date          object
Ship Mode           object
Segment             object
Country             object
City                object
State               object
Postal Code          int64
Region              object
Category            object
Sub Category        object
Product Id          object
cost price           int64
List Price           int64
Quantity             int64
Discount Percent     int64
dtype: object

In [ ]:
# Changing data type of Order Date column
df['Order Date'] = pd.to_datetime(df['Order Date'], format = '%Y-%m-%d')
df.dtypes

Order Id                     int64
Order Date          datetime64[ns]
Ship Mode                   object
Segment                     object
Country                     object
City                        object
State                       object
Postal Code                  int64
Region                      object
Category                    object
Sub Category                object
Product Id                  object
cost price                   int64
List Price                   int64
Quantity                     int64
Discount Percent             int64
dtype: object

### **Correcting column names**

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

### **Adding necessary columns**

In [ ]:
# Deriving Discount column

df['discount'] = df['list_price']*df['discount_percent']*0.01

In [ ]:
# Deriving Sales Price column

df['sales_price'] = df['list_price'] - df['discount']

In [ ]:
# Deriving Profit column

df['profit'] = df['sales_price'] - df['cost_price']

### **Deleting unnecessary columns**

In [ ]:
df.drop(columns=['list_price','cost_price','discount_percent'], inplace=True)

### **Final look of the table**

In [ ]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sales_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

### **Exporting the Table to drive**

In [ ]:
from google.colab import drive   # colab .. not collab
drive.mount('drive')

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).

In [ ]:
df.to_csv('/content/drive/My Drive/df_orders.csv', encoding='utf-8', index = False)

# only My Drive parent directory works
# /content/drive/ is necessary

## **Loading Data to MS SQLServer database**

### **Trying to connect to SQLServer via ODBC**

In [ ]:
pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (334 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 334.7/334.7 kB 6.5 MB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.1.0

In [ ]:
import pyodbc

conn = pyodbc.connect(
    "Driver={SQL Server};"
    "Server=MONOZ;"
    "Database=MyDB;"
    "Trusted_Connection=yes;"
)
conn.connect()
cursor = conn.cursor()
cursor.execute("SELECT top 5 * FROM df_orders")
rows = cursor.fetchall()

# SQL Queries executed on SQLServer based on the Guiding Questions

### Top 10 highest reveue generating products

In [ ]:
select top 10 sub_category as products, round(sum(sales_price),2) as sales
from df_orders
group by sub_category
order by sales desc;

In [ ]:
products	sales
Phones	318008.3
Chairs	316825.1
Storage	215908
Tables	199361.2
Binders	196038.6
Machines	182901.7
Accessories	161604.6
Copiers	144358.9
Bookcases	110816.1
Appliances	103697.7

### Top 5 highest selling products in each region

In [ ]:
with cte as (
	select region, sub_category as products, round(sum(sales_price),2) as sales
	from df_orders
	group by region, sub_category
)
select * from (
	select ROW_NUMBER() over(partition by region order by sales desc) as rn, *
	from cte
	) A
where rn<=5

In [ ]:
rn	region	products	sales
1	Central	Chairs	82271.7
2	Central	Phones	69868.6
3	Central	Binders	54692.9
4	Central	Storage	44201.7
5	Central	Tables	37773.1
1	East	Phones	96934.8
2	East	Chairs	92762.6
3	East	Storage	69037.6
4	East	Machines	63835.2
5	East	Binders	51533.8
1	South	Phones	56065.6
2	South	Machines	52201
3	South	Chairs	43701.7
4	South	Tables	42251.3
5	South	Binders	35759.4
1	West	Chairs	98089.1
2	West	Phones	95139.3
3	West	Tables	81603.6
4	West	Storage	68068.4
5	West	Accessories	59029.4

### Month over month growth comparison for 2022 and 2023 sales

In [ ]:
with cte as(
	select month(order_date) as month, year(order_date) as year, round(sum(sales_price),2) as sales
	from df_orders
	group by order_date
	)
	select month,
	sum(case when year = 2022 then sales else 0 end) as Sales_2022,
	sum(case when year = 2023 then sales else 0 end) as Sales_2023
	from cte
	group by month
	order by month;

In [ ]:
month	Sales_2022	Sales_2023
1	94712.5	88632.6
2	90091	128124.2
3	80106	82512.3
4	95451.6	111568.6
5	79448.3	86447.9
6	94170.5	68976.5
7	78652.2	90563.8
8	104808	87733.6
9	79142.2	76658.6
10	118912.7	121061.5
11	84225.3	75432.8
12	95869.9	102556.1

### Highest monthly sales for each category

In [ ]:
with cte as(
	select month(order_date) as month, category, round(sum(sales_price),2) as sales
	from df_orders
	group by order_date, category
	)
	select * from(
		select ROW_NUMBER() over(partition by month order by sales desc) as rn, *
		from cte
		) A
		where rn = 1 --highest sales only

In [ ]:
rn	month	category	sales
1	1	Technology	9007.5
1	2	Office Supplies	10474.6
1	3	Office Supplies	6840.9
1	4	Technology	10976
1	5	Technology	5562.4
1	6	Technology	8596.6
1	7	Office Supplies	6294.5
1	8	Technology	19458.2
1	9	Technology	6064.6
1	10	Technology	23064.4
1	11	Technology	10128
1	12	Technology	7158.5

### Product with highest growth by profit in 2023 compare to 2022

In [ ]:
with cte as (
	select sub_category, round(sum(profit),2) as profit, year(order_date) as year
	from df_orders
	group by year(order_date), sub_category
	)
	select *, (profit_2023-profit_2022) as Growth
	from (
		select sub_category,
		sum(case when year = 2022 then profit else 0 end) as profit_2022,
		sum(case when year = 2023 then profit else 0 end) as profit_2023
		from cte
		group by sub_category
		) A
		order by Growth desc

In [ ]:
sub_category	profit_2022	profit_2023	Growth
Machines	7243.2	10878.5	3635.3
Phones	13024.7	15343.6	2318.9
Binders	8685.5	10523.1	1837.6
Storage	8907.4	10630.6	1723.2
Accessories	7387.2	8057.4	670.2
Supplies	1500.7	1937.4	436.7
Chairs	14725.3	15089.8	364.5
Envelopes	607.2	640	32.8
Art	924.1	935.7	11.6
Fasteners	40.1	8.8	-31.3
Labels	349.6	295.3	-54.3
Paper	3058.9	2942.4	-116.5
Bookcases	5459.5	5036.6	-422.9
Furnishings	4236.2	3342.1	-894.1
Tables	10315.9	8275.3	-2040.6
Appliances	6374.4	3893.3	-2481.1
Copiers	8780.3	5718.6	-3061.7